!
!  Sub_write_b.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/20/2013 1:56:23 AM
!

subroutine Sub_write_b
use module_solid
implicit none
!=============DATA Write================
	  open (100,file='data_before.txt')
	  do i=1,dimm
	  do j=1,dimm
	  write(100,*) i,j,t(i,j)
	  end do
	  end do
	  !=======================================
	  !=======================================
      
end 