!
!  sub_laplace.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/21/2013 3:31:56 PM

subroutine sub_laplace()
use module_solid
implicit none

do k=1,k_laplace
	  do i=1,ie
	  do j=2,je-1
	  if (s(i,j)==1) then
	  t(i,j)=(t0(i,j+1)+t0(i,j-1)+t0(i+1,j)+t0(i-1,j))/4.0
	  end if
	  end do
	  end do
	  t0=t
end do

end