!
!  Sub_write_a.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/20/2013 1:56:39 AM
!
subroutine Sub_write_a
use module_solid
implicit none
!=============DATA Write================
	  open (100,file='data_after.txt')
	  do i=1,dimm
	  do j=1,dimm
	  write(100,*) i,j,S(i,j)
	  end do
	  end do
	  !=======================================
	  !=======================================
      
end 