!
!  ConsoleApp.f90
!
!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  10/20/2013 12:59:10 AM
!

      program UndercoolingSolid
	  use module_solid
	  implicit none
	  !=======================================
	  !=======================================
	  kE=50
	  iE=dimm
	  jE=dimm

	  Q0L=10.0
	  Q0S=-10.0
	  
	  T0L=-10.0 ! super cooled liquid, so its temperature is less than the solid
	  T0S=0.0 ! temperature of solid

	  C=0.1 ! Heat  capacity of the undercooled liquid
	  
	  k_s1=0.30
	  k_l1=0.11
	  k_s2=0.7*k_s1
	  k_l2=0.7*k_l1
	  !=======================================
	  !=======================================
	  !allocate (Q(dimm,dimm),T(dimm,dimm),S(dimm,dimm))
	  
	  Q=Q0L ! liquid latent heat
	  T=T0L ! liquid temperature
	  S=1 ! 1:liquid , 0:solid
	  
	  Do i=1,ie
	  do j=1,17+int(3*sin(real(i)*3.14*1.0/real(dimm)))
	  S(i,j)=0 ! 1:liquid , 0:solid
	  Q(i,j)=Q0S ! solid latent heat
	  T(i,j)=T0S ! solid temperature
	  end do
	  end do
	  T0=T
	  Q0=Q
	  !=======================================
	  !=======================================
	  k_laplace=50
	  call sub_laplace()
	  !=======================================
	  !=======================================
	  Do i=1,ie
	  do j=1,25+int(10*sin(real(i)*3.14*4.0/real(dimm)))
	  S(i,j)=0 ! 1:liquid , 0:solid
	  Q(i,j)=Q0S ! solid latent heat
	  T(i,j)=T0S ! solid temperature
	  end do
	  end do
	  T0=T
	  Q0=Q
	  !=======================================
	  !=======================================
	  k_laplace=2
	  call sub_laplace()

	  call sub_write_b()
	  call sub_write_a()
	  !=======================================
	  !=======================================
		!**********************************
		if (1==1) then
		Q=10.0
		k_laplace=1
	  do k=1,1000
	  Q0=Q
	  s0=s
	  t0=t
	  do i=1+1,iE-1
	  do j=1+1,jE-1
	  if (S0(i,j)==1) then
	  sum_s0=s0(i,j+1)+s0(i,j-1)+s0(i+1,j)+s0(i-1,j)
	  sum_s0=sum_s0+s0(i+1,j+1)+s0(i-1,j-1)+s0(i+1,j-1)+s0(i-1,j-1)

		if(sum_s0<8) then
		Q(i,j)=Q(i,j)-1.0/real(sum_s0)
		   if (Q(i,j)<0)then
		   s(i,j)=0
		   t(i,j)=t0s
		   endif
		endif
		
	  end if
	  end do
	  end do
	  !------------------------------------------------------
	  call sub_laplace()
	  end do

		end if


	  !==============time propagation=========
	  if (1==2)then
	  k_laplace=1
	  do k=1,kE
	  Q0=Q
	  s0=s
	  t0=t
	  do i=1+1,iE-1
	  do j=1+1,jE-1
	  if (S0(i,j)==1) then
	  sum_s0=s0(i,j+1)+s0(i,j-1)+s0(i+1,j)+s0(i-1,j)
		if(sum_s0<4) then
		sum_dt=abs(0)
		Q(i,j)=Q(i,j)-alpha
		alpha=alpha+kapa*abs(0)
		S(i,j+1)=0

		   if (Q(i,j)<0)then
		   s(i,j)=0
		   t(i,j)=t0s
		   endif
		endif
		
	  end if
	  end do
	  end do
	  !------------------------------------------------------
	  call sub_laplace()
	  end do
	  endif
      !=======================================
	  !=======================================
	  call sub_write_a()

	  end program UndercoolingSolid
