!
!  ConsoleApp.f90
!
!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  6/1/2013 10:58:19 PM
!

      program prog

      implicit none

      ! Variables

      ! Body

      end program prog
