!
!  ConsoleApp.f90
!
!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  10/9/2013 11:02:39 PM
!

      program prog

      implicit none
	  real::teta,f,p
	  p=4*atan(1.d0)/180.d0
	  open(100,file="data.txt")
	  do teta=0.d0,180.d0,2.d0
	  	  
	  f=(1.d0-cos(teta*p))*(1.d0-cos(teta*p))*(2.d0+cos(teta*p))/4.d0
	  write(100,*)teta,sqrt(f)
	  end do
	  !====================================
	  open(200,file="data2.txt")

	  do teta=0.d0,0.8d0,.005d0

	  f=(teta**2)*(1.d0-2.1d0*(teta**2))
	  write(200,*) teta,f
	  end do
	  
      end program prog
